# Generated by Django 5.0.6 on 2024-06-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='durations',
            field=models.CharField(default='10:12', max_length=10),
        ),
    ]
